defaults:
  - tasks: new_tasks
_target_: calvin.rollout.rollout.Rollout
_recursive_: false
env_cfg:
  _target_: vr_env.envs.play_lmp_wrapper.PlayLMPWrapper
skip_epochs: 1
rollout_freq: 1
video: true
num_rollouts_per_task: 10
check_percentage_of_batch: 1  # which percentage of sequences do we want to check for possible tasks
replan_freq: 30
ep_len: 120
empty_cache: true
log_video_to_file: false
save_dir: ./videos
start_robot_neutral: false
add_goal_thumbnail: true
min_window_size: ${datamodule.datasets.vision_dataset.min_window_size}
max_window_size: ${datamodule.datasets.vision_dataset.max_window_size}
id_selection_strategy: "select_longest"
lang_folder: "10inst_play_sbertMPNet"
