_target_: calvin_agent.datasets.shm_dataset.ShmDataset
key: "lang"
batch_size: 32
min_window_size: 16
max_window_size: 32
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
pad: true
lang_folder: "lang_annotations"
num_workers: 2
